### ISSUE TITLE
Friendly error message when input has syntax error

### ISSUE THREAD

**Issue by fzyzcjy** [fzyzcjy/dart_interactive#2]

**Comment by Keithcat1** [comment]
The way to get the reason why a hot reload failed from a ReloadReport is:
```
report.json?['notices'][0]['message'];
```
I might have noticed that the message sometimes weirdly formatted though, some kind of conversion might be needed.

**Comment by fzyzcjy** [comment]
@Keithcat1 That looks good. Feel free to PR!

**Comment by fzyzcjy** [comment]
We can firstly land a minimal version, and later reformat etc
