### ISSUE TITLE
Add thanks (all-contributors)

### ISSUE THREAD

**Issue by fzyzcjy** [fzyzcjy/dart_interactive#29]

**Comment by fzyzcjy** [comment]
@all-contributors please add @fzyzcjy for code, doc, ideas

**Comment by fzyzcjy** [comment]
@all-contributors please add @mraleph for ideas

**Comment by fzyzcjy** [comment]
@all-contributors please add @maks for ideas

**Comment by fzyzcjy** [comment]
@all-contributors please add @BlackHC for ideas

**Comment by maks** [comment]
@fzyzcjy please don't include me in the list of contributors as I haven't actually contributed to this repo. If you have used code from my https://github.com/maks/dart_repl project, it's sufficient to just mention its use under the BSD as required by the license. Thanks.

**Comment by fzyzcjy** [comment]
@maks Ah I include you as "ideas" (not "code"), since you made a prototype around this topic. If you insist, I can remove you.
