### ISSUE TITLE
Check whether `dart:mirror` is removeable

### ISSUE THREAD

**Issue by fzyzcjy** [fzyzcjy/dart_interactive#40]

**Comment by maks** [comment]
I'm not clear if it's possible, as I don't know if you can use the [reflectable package](https://pub.dev/packages/reflectable) due to using mirrors at runtime, but this would be worth investigating, as by depending on mirrors, this package won't be usable in Flutter or Dart Web (JS).

**Comment by fzyzcjy** [comment]
@maks `dart:mirror` dependency removed :)

**Comment by fzyzcjy** [comment]
That package looks interesting, thanks!
