### ISSUE TITLE
repl package name for pub

### ISSUE THREAD

**Issue by maks** [fzyzcjy/dart_interactive#42]
I'm happy to see you are keen to progress this work on a Dart REPL, you've made excellent progress so far and I currently don't have time to keep working on it, so if you would like, I'd happy to move the `repl` package name on Pub over to your publisher account so that you can make use of it for this package and I can deprecate and archive my repo.

**Comment by fzyzcjy** [comment]
Thank you! But I like the "interactive" name as well. 

> and I can deprecate and archive my repo.

This reminds me of a common practice in github community: When user A does not have time keep maintaining a package, will add a line README saying "please see user B's package B" and archive the github repo / deprecate the pub. Anyway this surely depends on you :)

**Comment by maks** [comment]
I've now updated my packages Readme to point to this package. Thanks again for making a fully usable Dart REPL! 👍🏻

**Comment by fzyzcjy** [comment]
You are welcome and thanks for your prior work!
