### ISSUE TITLE
Cannot run two shells at the same time

### ISSUE THREAD

**Issue by sebthom** [fzyzcjy/dart_interactive#54]
**Describe the bug**
Trying to run two shells at the same time results in `Could not start the VM service: localhost:8181 is already in use.`

**To Reproduce**
Run the `interactive` command in two separate terminal windows.

**Expected behavior**
Both interactive shells work.

**Additional context**
As a solution, the shell could either 
- automatically assigns a free port, or
- a port for ` --enable-vm-service=<[<port>[/<bind-address>]]>` could be provided using a command line option.

**Comment by fzyzcjy** [comment]
Feel free to PR! the two solutions both LGTM
