### ISSUE TITLE
FEATURE/DOC: Is this possible to host in integration test ?

### ISSUE THREAD

**Issue by runyaga** [fzyzcjy/dart_interactive#58]
**Is your feature request related to a problem? Please describe.**
The integration test cycle iteration is very long.  The first thing I wanted to reach for when we started was a REPL.
At this point we have grok'ed enough of how integration tests work and have most things built out.  

**Describe the solution you'd like**
Explanation of how to host a REPL in dart/flutter integration test so can interactively poke at tree, perform pump and tap.

**Comment by fzyzcjy** [comment]
Something like this come into my mind:

```dart
late WidgetTester tester;
final end = Completer();
void f() {
  testWidgets('', (t) async {
    tester = t;
    await end.future;
  });
}

f(); // may need somehow further work to let test start
```

then in REPL:

```
tester.pump(); .tap() etc
```

is acceptable
