### ISSUE TITLE
🐛 Bug: `[STDERR] The system cannot find the path specified` on Windows 11

### ISSUE THREAD

**Issue by coder0107git** [fzyzcjy/dart_interactive#67]
### Description
Running shell commands in the interactive console produces the errors `[STDERR] The system cannot find the path specified` and `[WARNING <date>] Process execution failed (exitCode=1)`.

### Steps to reproduce the behavior:
1. Install the package if not already installed (make sure the install location is on your path and using the latest version).
2. Start the package.
3. Run `!dart pub add device_info_plus` or `!dart pub add path`.
4. See the error

### Expected behavior
The package to install and work like normal.

<details>
<summary><h3>Screenshots</h3></summary>

Git Bash:
![git-bash-dart-interactive-error](https://user-images.githubusercontent.com/76132013/211135194-1fabbae8-3a2f-4bed-8b2f-f2b4ce75a7dc.png)

PowerShell:
![powershell-dart-interactive-error](https://user-images.githubusercontent.com/76132013/211135297-28a18571-4e21-4ca9-bfbf-98f5be684014.png)

Command Prompt:
![command-prompt-dart-interactive-error](https://user-images.githubusercontent.com/76132013/211170669-7e6dc85c-4695-41bb-999d-4adceea47907.png)

</details>

### Desktop:
 - OS: `Windows 11`
 - Edition: `Home`
 - Version: `22H2`
 - Build: `22621.963`

**Comment by fzyzcjy** [comment]
Hmm looks like cannot find the `dart` command?

**Comment by coder0107git** [comment]
The odd thing is I have the `dart` command in my path. I checked by running `dart --version` in Git Bash, PowerShell, and Command Prompt (all produced the same result, `Dart SDK version: 2.18.6 (stable) (Tue Dec 13 21:15:14 2022 +0000) on "windows_x64"`).

**Comment by fzyzcjy** [comment]
Feel free to debug by, e.g. downloading source code and `dart run` and print out some logs! I guess it may be caused by how dart's execute-process command different from normal

**Comment by coder0107git** [comment]
I `git clone`d the repo, ran `dart pub get` in `dart_interactive/packages/interactive`, and ran `dart run --verbosity=all` in the same folder. I got the same errors (even when I ran `!whoami`).

**Comment by fzyzcjy** [comment]
Yes, that's why I guess it is a problem of Dart `Process` class

**Comment by coder0107git** [comment]
I'm not sure I understand. Is it a problem with my dart install or this package?

**Comment by fzyzcjy** [comment]
Maybe a problem of how this package incorrectly(?) uses the Dart`Process`. Thus, I would suggest creating a minimal reproducible sample, such as a bare metal dart file with a few lines calling a process like `whoami` as you have said, and see what happens.
