### ISSUE TITLE
Suggestions: VS Code extension and Jupyter Notebook integration

### ISSUE THREAD

**Issue by JordyScript** [fzyzcjy/dart_interactive#76]
First of all, thank you very much for building and maintaining such an awesome project! 

I'm not sure if this is the right place to leave these ideas, but I also don't know where else to go with them, and I do not have the capacity to execute these ideas on my own, so I'll be offering two suggestions here for you and others interested in interactive dart to see and hopefully that will kickstart a conversation. 

### VS Code Extension

A VS Code extension providing functionality to run a line / selection in the terminal similar to the Python extension would be really helpful. When you activate the extension by pressing the Shift+Enter shortcut key, the Python extension will create a new terminal and open a python REPL if this has not been done yet, and then it will execute the line where the cursor is located or the selected text (possibly multiline). The dart interactive extension could provide the same functionality using this project as the REPL. 

### Jupyter Notebook Integration

Jupyter Notebooks allow for literate programming, keeping markdown formatted text, code, and code output together in single document. Jupyter notebooks can use a variety of kernels such as python, or julia, and using this project dart could be the next language to be added. Dart has a relatively small data science ecosystem, but with tools like dart interactive, it could allow for a more vibrant data science ecosystem to develop. Regardless of data science, for the more general use case of literate programming (or simply iterative and exploratory development) having jupyter notebook integration would still be a positive development that would also draw more attention to this project.

What do you think? Is anyone interested in (either of) these ideas? Does anyone know how to go about implementing them? Or is anyone aware of a more appropriate place to discuss these things?

**Comment by fzyzcjy** [comment]
Yes, definitely! Dart-interactive was created because I wanted a Jupyter Notebook and/or a Intellij IDEA IPython (similar to VSCode extension you mentioned) for Dart (instead of Python). I guess many people also want this because of that (see https://github.com/dart-lang/sdk/issues/39965). 

However, it seems that the part that is a bit hard to implement is the dart-interactive, and the rest (extension, jupyter integration) is a bit simpler and is engineering work. Thus, given that my time is quite limited, I have no time to do the rest.

If anyone is interested, I am happy to provide suggestions and hints :)

**Comment by so1ve** [comment]
bump

**Comment by citizen428** [comment]
I quickly hacked something together for Emacs on top of `comint`, took about half an hour. There's a lot left to do but the basics are working for now.

<img width="1579" alt="Screenshot 2023-05-18 at 10 45 19" src="https://github.com/fzyzcjy/dart_interactive/assets/47985/96193051-27e3-45f5-b0a2-8bcebc448df3">

**Comment by fzyzcjy** [comment]
Looks interesting!

**Comment by citizen428** [comment]
> Looks interesting!

Code here in case anyone wants to have a look or help out to get this to the same level as similar packages:

https://sr.ht/~citizen428/inf-dart/
