### ISSUE TITLE
Does dart interactive work in the browser?

### ISSUE THREAD

**Issue by jlewi** [fzyzcjy/dart_interactive#80]
Does dart interactive work in the browser? My naive understanding is that dart_interactive relies on the Dart VM. IUC on the web Dart compiles to JS and doesn't rely on the Dart VM [docs](https://dart.dev/resources/faq#q-will-the-dart-vm-get-into-chrome).
Is there any path to creating a dart REPL on the web?

**Comment by fzyzcjy** [comment]
Yes I think so.

As for web, I guess it may be hard. For example, even flutter does not support hot reload on web https://github.com/flutter/flutter/issues/53041 . Maybe we can wait for that issue, and if that is supported maybe we have enough infra to implement it?

**Comment by jlewi** [comment]
@fzyzcjy Could you explain how you think this might work on the web? I think for this discussion we can ignore flutter.
IUC dart on mobile/desktop relies on JIT and a VM which allows for a REPL. However, on web I believe dart is compiled to JS and then executed. Is there someway to run the dart VM on web?

**Comment by fzyzcjy** [comment]
@jlewi I have not heard of any. I am not sure, maybe we need to wait for new Dart features if possible?

**Comment by fzyzcjy** [comment]
The reason why I say wait for flutter is that, if flutter does that successfully, then it may mean that Dart supports vm on web, or dart provides a new infra, etc, then we can utilize it.
