### ISSUE TITLE
When Backspace key is pressed on the terminal it doesn't remove the characters and give 

### ISSUE THREAD

**Issue by Udesh-Ranjan** [fzyzcjy/dart_interactive#81]
In the very first line I miss spelled the during importing the library so I pressed the `<-` (left arrow) key of keyboard  it didn't respond to it and the cursor didn't move from its place.

In order to fix it I pressed backspace key multiple times but it didn't delete the previous characters and rather than that just moved the cursor towards left side.

In the second import statement I typed everything correctly (no backspace) and pressed enter it worked.

### Below is the screen sort of my terminal

![vlcsnap-2023-04-08-10h48m33s809](https://user-images.githubusercontent.com/54318997/230704665-3ed46f39-18a6-4a1c-a581-f29506a7747f.png)

### Platform information

- **Terminal** : [Conemu64](https://conemu.github.io/)
- **OS**          : Microsoft Windows NT 10.0.22621.0 (Windows 11)
- **Dart**        : Dart SDK version: 2.19.4 (stable) (Tue Mar 7 09:58:46 2023 +0000) on "windows_x64"

**Comment by fzyzcjy** [comment]
Hmm is it a bug of https://github.com/fzyzcjy/dart_interactive/blob/23159df0f9d6598885a19dc1ec4c26a6f2442797/packages/interactive/pubspec.yaml#L12?

**Comment by mingpepe** [comment]
> Hmm is it a bug of
> 
> https://github.com/fzyzcjy/dart_interactive/blob/23159df0f9d6598885a19dc1ec4c26a6f2442797/packages/interactive/pubspec.yaml#L12
> 
> ?

It's a limitation on Windows for arrow key. https://github.com/jathak/cli_repl/issues/12
Can use Ctrl-B and Ctrl-F to replace left and right arrow key.
