### ISSUE TITLE
why define a variable without var keyword?

### ISSUE THREAD

**Issue by Silentdoer** [fzyzcjy/dart_interactive#84]
**Describe the bug**
it's not consistent with language?

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by fzyzcjy** [comment]
You are right. But the REPL is indeed quite hacky, and removing the var keyword is the way I have come up with to perfectly implement everything.

However, if you hate the removal of var keyword, feel free to PR!
