### ISSUE TITLE
fails to launch

### ISSUE THREAD

**Issue by asmrtfm** [fzyzcjy/dart_interactive#92]
Following these instructions:

["Getting started"](https://pub.dev/packages/interactive#-getting-started)
> Install (just standard procedure of installing global dart packages):
`dart pub global activate interactive`
> Use (just a normal binary):
`interactive`

Results in this error:
```
Run: /usr/bin/flutter/bin/cache/dart-sdk/bin/dart [--enable-vm-service=34467, file:///home/me/.pub-cache/global_packages/interactive/bin/interactive.dart-3.4.0.snapshot, --vm-service-was-enabled]
Workspace: /tmp/dart_interactive_workspace_2024-05-14T174404964295
The Dart VM service is listening on http://127.0.0.1:34467/rR3gWUo72JQ=/
The Dart DevTools debugger and profiler is available at: http://127.0.0.1:34467/rR3gWUo72JQ=/devtools?uri=ws://127.0.0.1:34467/rR3gWUo72JQ=/ws
```

**Comment by fzyzcjy** [comment]
Hi, do you see `>>>`?

For me I see:

```
(base) ➜  research_mono git:(master) interactive
Run: /Users/tom/fvm/versions/3.19.2/bin/cache/dart-sdk/bin/dart [--enable-vm-service=62128, file:///Users/tom/.pub-cache/global_packages/interactive/bin/interactive.dart-3.3.0.snapshot, --vm-service-was-enabled]
The Dart VM service is listening on http://127.0.0.1:62128/ID8JjrzMOfw=/
The Dart DevTools debugger and profiler is available at: http://127.0.0.1:62128/ID8JjrzMOfw=/devtools?uri=ws://127.0.0.1:62128/ID8JjrzMOfw=/ws
Workspace: /var/folders/j5/j6ymn7yd70564hzt31pq_0g80000gn/T/dart_interactive_workspace_2024-05-15T082218312739
>>> a=1
1
```

And btw, check whether you have http proxy set.

**Comment by asmrtfm** [comment]
no it just dumps me back out to my normal bash prompt
I do not have any proxies.
I'm running on ubuntu 22.04 with dart installed via the instructions on their page using their official binary (not snap)

**Comment by fzyzcjy** [comment]
Hmm, so I guess one way is to run it by source, and add a lot of `print` here and there (or use your favorite debugger), to see where it gets stucked.

**Comment by asmrtfm** [comment]
didn't have time to gather/provide actually valuable debug data and it felt rude to leave this open.
